# Site Settings
title:               Numerical simulations blog
tagline:             by spolanski
description:
baseurl:            #"/blog"
url:                #"https://spolanski.github.io"
github:
  url:               #"https://spolanski.github.io/blog"
author:
  name:              "Slawomir Polanski"
  email:             "polanski.slawomir@gmail.com"
  github:            "spolanski"
  linkedin:          "slawomirpolanski"
navigation:
- title: About
  url: /about
- title: Writing
  url: /writing
- title: Contact
  url: /contact

paginate:            5
disqus:              disqus_BO4VASjAb2#"your-disqus"

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
gems:                [jekyll-paginate]
